version: '3.9'

services:
  cassandra:
    image: cassandra:3.11.17
    restart: always
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_DC: datacenter1
    volumes:
      - cassandra-data:/var/lib/cassandra

#  kafka:
#    image: bitnami/kafka:3.4.0
#    restart: unless-stopped
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,INTERNAL://:9094,CONTROLLER://:9093
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
#      - KAFKA_CFG_BROKER_ID=1
#      - KAFKA_CFG_NODE_ID=1
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    ports:
#      - "9092:9092"
#    volumes:
#      - kafka-data:/bitnami/kafka
#
  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    restart: unless-stopped
    ports:
      - "9092:9092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    command: redpanda start --smp 1 --overprovisioned --kafka-addr PLAINTEXT://0.0.0.0:9094,OUTSIDE://0.0.0.0:9092 --advertise-kafka-addr PLAINTEXT://kafka:9094,OUTSIDE://localhost:9092 --pandaproxy-addr 0.0.0.0:8082 --advertise-pandaproxy-addr localhost:8082

  redpanda_console:
    image: docker.redpanda.com/redpandadata/console:latest
    restart: unless-stopped
    ports:
      - "8999:8080"
    environment:
      - KAFKA_BROKERS=kafka:9094
    depends_on:
      - kafka

  url:
    image: url:latest
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - cassandra
      - kafka
    profiles:
      - app

volumes:
  cassandra-data:
  kafka-data:
  redpanda-data:
